[project]
name = "skyvern-llamaindex"
version = "0.2.1"
description = "Skyvern integration for LlamaIndex"
authors = [{name = "lawyzheng", email = "lawy@skyvern.com"}]
readme = "README.md"
requires-python = ">=3.11,<3.14"

dependencies = [
    "skyvern>=0.2.0",
    "llama-index>=0.12.19",
]


[project.optional-dependencies]
dev = [
    "twine>=6.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["skyvern_llamaindex"]
