[project]
name = "skyvern-langchain"
version = "0.2.0"
description = ""
authors = [{name = "lawyzheng", email = "lawy@skyvern.com"}]
readme = "README.md"
requires-python = ">=3.11,<3.14"

dependencies = [
    "skyvern>=0.2.0",
    "langchain>=0.3.19",
]


[project.optional-dependencies]
dev = [
    "twine>=6.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["skyvern_langchain"]
